replicaCount: 1

nameOverride: python-final-project
fullnameOverride: python-final-project

image:
  repository: your-dockerhub-username/your-image
  tag: "latest"
  pullPolicy: IfNotPresent

app:
  port: 8080
  dataDir: /data

persistence:
  enabled: true
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  size: 1Gi

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  ingressClassName: nginx
  host: app.shpakova.devops10.test-danit.com
  tls:
    secretName: app-tls
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-ingress-class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"